<?php

return [
    'supported' => [
        'PKR' => 'Pakistani Rupee',
        'USD' => 'US Dollar',
        'AED' => 'UAE Dirham',
        'EUR' => 'Euro',
        'GBP' => 'British Pound',
        'SAR' => 'Saudi Riyal',
        'CAD' => 'Canadian Dollar',
        'AUD' => 'Australian Dollar',
        'JPY' => 'Japanese Yen',
        'CNY' => 'Chinese Yuan',
        'INR' => 'Indian Rupee',
        'BDT' => 'Bangladeshi Taka',
        'NPR' => 'Nepalese Rupee',
        'LKR' => 'Sri Lankan Rupee',
        'QAR' => 'Qatari Riyal',
        'KWD' => 'Kuwaiti Dinar',
        'BHD' => 'Bahraini Dinar',
        'OMR' => 'Omani Rial',
        'MYR' => 'Malaysian Ringgit',
        'SGD' => 'Singapore Dollar',
        'IDR' => 'Indonesian Rupiah',
        'THB' => 'Thai Baht',
        'VND' => 'Vietnamese Dong',
        'PHP' => 'Philippine Peso',
        'KRW' => 'South Korean Won',
        'HKD' => 'Hong Kong Dollar',
        'NZD' => 'New Zealand Dollar',
        'TRY' => 'Turkish Lira',
        'CHF' => 'Swiss Franc',
        'SEK' => 'Swedish Krona',
        'NOK' => 'Norwegian Krone',
        'DKK' => 'Danish Krone',
        'RUB' => 'Russian Ruble',
        'ILS' => 'Israeli Shekel',
        'ZAR' => 'South African Rand',
        'EGP' => 'Egyptian Pound',
        'NGN' => 'Nigerian Naira',
        'KES' => 'Kenyan Shilling',
        'BRL' => 'Brazilian Real',
        'MXN' => 'Mexican Peso',
    ],
];
